version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    restart: always
    volumes:
      - ollama_data:/root/.ollama
      - openwebui_data:/app/backend/data
    ports:
      - "3000:8080"
    networks:
      - default

volumes:
  ollama_data:
  openwebui_data:

